apiVersion: v1
data:
  # echo "internal-authorization-db-app-user" | base64
  password: aW50ZXJuYWwtYXV0aG9yaXphdGlvbi1kYi1hcHAtdXNlcgo=
  username: aW50ZXJuYWwtYXV0aG9yaXphdGlvbi1kYi1hcHAtdXNlcgo=
kind: Secret
metadata:
  name: internal-authorization-db-app-user
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: internal-authorization-db

spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  postgresql:
    parameters:
      random_page_cost: "1.1"
      log_statement: "ddl"
      log_checkpoints: "on"

  storage:
    storageClass: "nfs-rwx"
    size: "2Gi"

  bootstrap:
    initdb:
      database: app
      owner: internal-authorization-db-app-user
      secret:
        name: internal-authorization-db-app-user

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false

# delete with :
#   kubectl delete cluster --name internal-authorization-db-app-user
#   kubectl delete secret internal-authorization-db-app-user -n testing-dev